#!/usr/bin/env python
import sys, os
from os.path import *

NAME = os.path.basename(__file__)
# We import jsmin which is distributed with V8
sys.path.append(join(dirname(dirname(abspath(__file__))), "deps","v8","tools"))
import jsmin

HELP = """
%s FILE NAME

Converts the given file to a C const char array that you can embed in a K7 native module file

ex: %s module1.js
""" % (NAME, NAME)

if len(sys.argv) != 2:
	print HELP
else:
	source = sys.argv[1]
	name   = os.path.basename(source).replace(".","_").upper()
	f = file(source,'r')
	r = []
	for c in jsmin.jsmin(f.read()):
		if c == "'":
			r.append("'\\''")
		else:
			r.append(repr(c))
	r.append("'\\0'")
	print "static const char %s[] = {%s};" % (name, ",".join(r))
